def includeme(config):
    config.add_static_view('static', 'static', cache_max_age=3600)
    config.add_route('host_create', '/host_create')
    config.add_route('host_form', '/host/form')
    config.add_route('main', '/')
    config.add_route('host', '/host/{id}')
    config.add_route('host_list', '/host')
    config.add_route('domain_list', '/domain')
    config.add_route('domain_list_json', '/domains.json')
    config.add_route('domain', '/domain/{id}')
    config.add_route('domain_form', '/domain_form')
    config.add_route('domain_create', '/domain_create')
    config.add_route('service_list', '/svc')
    config.add_route('service', '/svc/{id}')
    config.add_route('root', '/root')
    config.add_route('login', '/login')
    config.add_route('logout', '/logout')

